name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: test-host
    if: BUILD_STATUS.repository == 'true'
    steps:
      - name: Print greeting
        run: echo "Hello"
      - name: Print goodbye
        run: echo "bye"
