name: firstaction Workflow
on: 
  push
jobs:
  first-job:
    runs-on: win-run

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Load environment variables
        uses: xom9ikk/dotenv@v2.2.0
        with:
            mode: test
            path: ./env_variable/

      - name: Read Artifact Content
        run: |
          echo  "DEPLOY_STATUS from env file: ${{ env.DEPLOY_STATUS }}"
          Write-Host "BUILD_STATUS from env file: ${{ env.BUILD_STATUS }}"

      - name: Use BUILD_STATUS in an If Condition
        run: |
          if ($BUILD_STATUS -eq "true") {
            Write-Host "BUILD_STATUS is true"
          } else {
            Write-Host "BUILD_STATUS is false"
          }
