name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: test-host
    environment: development
    if: ${{ vars.BUILD_STATUS1 == 'true' }}
    steps:
      - name: Print greeting
        run: echo "Hello-hi-hello"
      - name: Print goodbye
        run: echo "bye"
      - name: Run Powershell script
        shell: pwsh
        run: |
           $mysecretvalue = $env.GITHUB_NEXUS_USERNAME
           Write-Host "My Secret username is $mysecretvalue"
