name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: win-run
    environment: development
    #if: ${{ vars.BUILD_STATUS == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read variables.txt and Set Environment Variables
        run: |
          for /f "usebackq delims=" %%a in (variables.txt) do (
            set %%a
          )

      - name: Print BUILD_STATUS
        run: |
          echo BUILD_STATUS=%BUILD_STATUS%



      - name: Use BUILD_STATUS in If Condition (PowerShell)
        run: |
          if ($env:BUILD_STATUS -eq "true") {
            Write-Host "BUILD_STATUS is true. Do something here..."
          } else {
            Write-Host "BUILD_STATUS is not true. Do something else..."
          }

        
          
          
