name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: test-host
    environment: Development
    #if: ${{ secrets.BUILD_STATUS == 'true' }}
    steps:
          - name: Print greeting
            run: echo ${{ vars.BUILD_STATUS }}
          - name: Print goodbye
            run: |
              # Read the contents of .env file
              envContents=$(cat .env)

              # Parse the contents and set environment variables
              while IFS= read -r line; do
              export "$line"
              done <<< "$envContents"

          - name: Print Environment Variables
            run: |
              echo "MY_VARIABLE=$MY_VARIABLE"
              echo "ANOTHER_VARIABLE=$ANOTHER_VARIABLE"
