name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: test-host
    environment: development
    #if: ${{ vars.BUILD_STATUS == 'true' }}
    steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: READ ENV FILE
            run: |
              # Read the contents of .env file
              envContents=$(cat .env.qa)

              # Parse the contents and set environment variables
              while IFS= read -r line; do
              export "$line"
              done <<< "$envContents"

          - name: Print Environment Variables
            run: |
              $BUILD = $env:BUILD_STATUS
              echo $BUILD
            env:
              BUILD: ${{ SECRETS.BUILD_STATUS }}
            
        
          
          
