name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: win-run
    environment: development
    #if: ${{ vars.BUILD_STATUS == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read .env File and Set Inputs      
        run: |
        
          Get-Content .env | ForEach-Object {
            $name, $value = $_ -split '=', 2
            Set-Item -Path "ENV:$name" -Value $value
            Write-Host "Setting input $name=$value"
          }

      - name: Print BUILD_STATUS
        run: |
          $buildStatus = (Get-Item -Path "ENV:BUILD_STATUS").Value
          echo "BUILD_STATUS=$buildStatus"

      - name: Use BUILD_STATUS in If Condition
        run: |
          $buildStatus = (Get-Item -Path "ENV:BUILD_STATUS").Value
          if ($buildStatus -eq "true") {
            echo "BUILD_STATUS is true. Do something here..."
          } else {
            echo "BUILD_STATUS is not true. Do something else..."
          }
