name: firstaction Workflow
on: 
  workflow_call:
    inputs:
        BUILD_STATUS:
        required: true
        type: string
jobs:
  on: 
    push
  first-job:
    runs-on: win-run
    env:
      BUILD_STATUS: ${{ inputs.BUILD_STATUS }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

         
          
      - name: Print BUILD_STATUS
        run: |
          echo "BUILD_STATUS=${{env.BUILD_STATUS}}"
      - name: Use BUILD_STATUS in If Condition
        run: |
          if (${{env.BUILD_STATUS}} -eq "true") {
            echo "BUILD_STATUS is true. Do something here..."
          } else {
            echo "BUILD_STATUS is not true. Do something else..."
          }
