name: firstaction Workflow
on: 
  push
jobs:
  first-job:
    runs-on: win-run
    env:
      BUILD_STATUS: ${{ inputs.BUILD_STATUS }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Read .env File and Set Inputs      
        run: |
          Get-Content .env | ForEach-Object {
            $name, $value = $_ -split '=', 2
            Set-Item -Path "ENV:$name" -Value $value
            Write-Host "$name=$value" >> $GITHUB_ENV
          }          
          
      - name: Print BUILD_STATUS
        run: |
          echo "value of the variable: $env:BUILD_STATUS"
