name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: win-run
    environment: development
    #if: ${{ vars.BUILD_STATUS == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get content  
        run: |
         Get-Content .env | ForEach-Object {
            $name, $value = $_ -split '=', 2
            $env:$name = $value
            Write-Host "Setting input $name=$value"
          }

      - name: Print BUILD_STATUS
        run: |
          Write-Host "BUILD_STATUS=$($env:BUILD_STATUS)"

      - name: Use BUILD_STATUS in If Condition
        run: |
          $envsPath = "${{ steps.export-vars.outputs.envs-path }}"
          $envs = Get-Content $envsPath | ConvertFrom-Json
          if ($envs.BUILD_STATUS -eq "true") {
            echo "BUILD_STATUS is true. Do something here..."
          } else {
            echo "BUILD_STATUS is not true. Do something else..."
          }
