name: firstaction Workflow
on: 
  push
jobs:
  first-job:
    runs-on: win-run
    env:
      BUILD_STATUS: ${{ inputs.BUILD_STATUS }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: variables.txt
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Read Artifact Content
        run: |
          # Read the content of the artifact file
          $artifactContent = Get-Content variables.txt

          # Extract the BUILD_STATUS value
          $BUILD_STATUS = ($artifactContent -match 'BUILD_STATUS=(.*)')[1]

          Write-Host "BUILD_STATUS from artifact: $BUILD_STATUS"

      - name: Use BUILD_STATUS in an If Condition
        run: |
          if ($BUILD_STATUS -eq "true") {
            Write-Host "BUILD_STATUS is true"
          } else {
            Write-Host "BUILD_STATUS is false"
          }
