name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: test-host
    environment: Development
    #if: ${{ secrets.BUILD_STATUS == 'true' }}
    steps:
          - name: Print greeting
            run: echo ${{ vars.BUILD_STATUS }}
          - name: Print goodbye
            run: echo "bye"
          - name: Load Environment Variables from .env
            run: pwsh -File load-env.ps1

          - name: Print Environment Variables
            run: |
              echo "MY_VARIABLE=$env:MY_VARIABLE"
              echo "ANOTHER_VARIABLE=$env:ANOTHER_VARIABLE"
