name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: test-host
    if: ${{ vars.BUILD_STATUS == 'true' }}
    steps:
      - name: Print greeting
        run: echo "Hello"
      - name: Print goodbye
        run: echo "bye"
