name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: test-host
    #environment: Development
    #if: ${{ secrets.BUILD_STATUS == 'true' }}
    steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: READ ENV FILE
            run: |
              # Read the contents of .env file
              envContents=$(cat qa.env)

              # Parse the contents and set environment variables
              while IFS= read -r line; do
              export "$line"
              done <<< "$envContents"

          - name: Print Environment Variables
            run: |
              echo "BUILD_STATUS=$MY_VARIABLE" >> ${{ vars.BUILD_STATUS }}
