name: firstaction Workflow
on: push
jobs:
  first-job:
    runs-on: win-run
    environment: development
    #if: ${{ vars.BUILD_STATUS == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read variables.env and Set Environment Variables
        run: |
            Get-Content -Path .env.qa | ForEach-Object {
            $name, $value = $_ -split '=', 2
            [Environment]::SetEnvironmentVariable($name, $value, 'Machine') }

      - name: Print Environment Variable
        run: |
          echo "BUILD_STATUS=$env:BUILD_STATUS"
        
          
          
